# Config for rendering the yaml templates

APP_NS: default
GW_NS: default
GW_NAME: default-gateway

APP_NAME: ext-auth
EXT_AUTH_HOST: authorizer.myorg.com
REDIRECT_URI: https://gateway.myorg.com/oidc/idpresponse

OIDC_ISSUERS: https://myorg.okta.com/oauth2/default?client_id=...&client_secret=...&scope=openid email profile address phone offline_access,https://myorg.okta.com?client_id=...&client_secret=...&scope=openid email profile address phone offline_access,https://cognito-idp.us-east-1.amazonaws.com/us-east-1_...?client_id=...&https://cognito-idp.us-west-2.amazonaws.com/us-west-2_...?client_id=...
